# Generated by Django 2.0.6 on 2018-06-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='unsold', max_length=60),
        ),
    ]
